sudo:required
services:
  - docker

before_install:
  - docker build -t belayfitsum/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true belayfitsum/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-central-1-977952712667"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"